version: '3.9'
services:
  php:
    image: webdevops/php-dev:8.1
    working_dir: /app
    container_name: cw-php
    volumes:
      - .:/app
    environment:
      - XDEBUG_MODE=develop,coverage
      - PHP_DISPLAY_ERRORS=1
      - PHP_DEBUGGER=xdebug
    #   - php.xdebug.default_enable=1
    #   - php.xdebug.remote_enable=1
    #   - php.xdebug.remote_handler=dbgp
    #   - XDEBUG_IDE_KEY="PHPSTORM"
    #   - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
    #   - XDEBUG_CLIENT_PORT=9000
    #   - XDEBUG_START_WITH_REQUEST=yes
    #   - XDEBUG_DISCOVER_CLIENT_HOST=yes
    #   - XDEBUG_REMOTE_AUTOSTART=1